# Generated by Django 4.1.6 on 2023-02-07 03:22

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=127)),
                ('phone', models.CharField(max_length=31)),
                ('birthdate', models.DateField()),
                ('id_type', models.CharField(choices=[('CI', 'Cedula'), ('PA', 'Pasaporte')], default='CI', max_length=2)),
                ('id_number', models.CharField(max_length=31, validators=[api.models.Driver.validate_alphanumeric])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15)),
                ('make', models.CharField(max_length=63)),
                ('status', models.CharField(choices=[('AC', 'Activo'), ('MA', 'Mantenimiento'), ('TA', 'Taller'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('usage_type', models.CharField(choices=[('KM', 'Kilometros'), ('HR', 'Horas')], default='KM', max_length=2)),
                ('usage', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('valid_thru', models.DateField()),
                ('renovation_alert', models.DateTimeField()),
                ('status', models.CharField(choices=[('VAL', 'Valido'), ('EXP', 'Expirado')], default='VAL', max_length=3)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriverDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('valid_thru', models.DateField()),
                ('renovation_alert', models.DateTimeField()),
                ('status', models.CharField(choices=[('VAL', 'Valido'), ('EXP', 'Expirado')], default='VAL', max_length=3)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
    ]
