# Generated by Django 4.1.6 on 2023-02-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('valud_thru', models.DateTimeField()),
                ('renovation_alert', models.DateTimeField()),
                ('status', models.CharField(choices=[('VAL', 'Valido'), ('EXP', 'Expirado')], default='VAL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('AC', 'Activo'), ('MA', 'Mantenimiento'), ('TA', 'Taller'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('usage_type', models.CharField(choices=[('KM', 'Kilometros'), ('HR', 'Horas')], default='KM', max_length=2)),
                ('usage', models.PositiveIntegerField()),
                ('documentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.documentation')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=63)),
                ('model', models.CharField(max_length=63)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vehiclemodel'),
        ),
    ]
