# Generated by Django 4.1.6 on 2023-02-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documentation_vehicle_vehiclemodel_delete_testmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=127)),
                ('phone', models.CharField(max_length=31)),
                ('dob', models.DateTimeField()),
                ('id_type', models.CharField(choices=[('CI', 'Cedula'), ('PA', 'Pasaporte')], default='CI', max_length=2)),
                ('id_number', models.CharField(max_length=31)),
                ('documentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.documentation')),
            ],
        ),
    ]
