# Generated by Django 4.1.6 on 2023-02-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_make_vehicle_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='notes',
        ),
    ]
