# Generated by Django 4.1.6 on 2023-02-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_documentation_valud_thru_alter_driver_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='valud_thru',
            new_name='valid_thru',
        ),
    ]
