# Generated by Django 4.1.6 on 2023-02-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vehicle_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='notes',
        ),
    ]
