# Generated by Django 4.1.6 on 2023-02-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vehicledocumentation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='documentation',
        ),
        migrations.AddField(
            model_name='driverdocumentation',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
        ),
        migrations.AddField(
            model_name='vehicledocumentation',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
    ]
