# Generated by Django 4.1.6 on 2023-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehicle_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocumentation',
            name='valid_thru',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledocumentation',
            name='valid_thru',
            field=models.DateField(blank=True, null=True),
        ),
    ]
