# Generated by Django 4.1.6 on 2023-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdocumentation',
            old_name='valid_thru',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='vehicledocumentation',
            old_name='valid_thru',
            new_name='expiry',
        ),
        migrations.RemoveField(
            model_name='driverdocumentation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vehicledocumentation',
            name='status',
        ),
        migrations.AlterField(
            model_name='driverdocumentation',
            name='renovation_alert',
            field=models.IntegerField(blank=True, choices=[(15, 'Fifteen Days'), (30, 'Thirty Days'), (45, 'Forty Five Days'), (60, 'Sixty Days')], null=True),
        ),
        migrations.AlterField(
            model_name='vehicledocumentation',
            name='renovation_alert',
            field=models.IntegerField(blank=True, choices=[(15, 'Fifteen Days'), (30, 'Thirty Days'), (45, 'Forty Five Days'), (60, 'Sixty Days')], null=True),
        ),
    ]
