# Generated by Django 4.1.6 on 2023-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_valid_thru_driverdocumentation_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocumentation',
            name='renovation_alert',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (15, 'Fifteen Days'), (30, 'Thirty Days'), (45, 'Forty Five Days'), (60, 'Sixty Days')], null=True),
        ),
        migrations.AlterField(
            model_name='vehicledocumentation',
            name='renovation_alert',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (15, 'Fifteen Days'), (30, 'Thirty Days'), (45, 'Forty Five Days'), (60, 'Sixty Days')], null=True),
        ),
    ]
